1) Evaluar cada uno de los 8 endpoints usando request.get()

In [5]:
import requests

resp_empresas_tic=requests.get("https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/71007?tip=AM")

In [6]:
#endpoint empresas TIC
#pregunta 1
resp_empresas_tic.status_code

200

In [7]:
resp_cifra_de_negocio=requests.get("https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/67903?tip=AM")

In [8]:
#endpoint cifra de negocio TIC
#pregunta 1, 2, 3
resp_cifra_de_negocio.status_code

200

In [9]:
resp_valor_añadido=requests.get("https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/67904?tip=AM")

In [10]:
#endpoint valor añadido sector TIC
#pregunta 1, 3
resp_valor_añadido.status_code

200

In [11]:
resp_num_ocupados=requests.get("https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/67901?tip=AM")

In [12]:
#endpoint número ocupados sector TIC
#pregunta 1,2,3
resp_num_ocupados.status_code

200

In [13]:
resp_coste_trabajador = requests.get("https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/75360?tip=AM")

In [14]:
#endpoint Coste salarial por trabajador y mes/hora
#pregunta 4
resp_coste_trabajador.status_code

200

In [15]:
resp_ia=requests.get("https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/71018?tip=AM")

In [16]:
#endpoint Inteligencia Artificial
#pregunta 5
resp_ia.status_code

200

In [17]:
resp_cloud_computing=requests.get("https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/76386?tip=AM")

In [18]:
#endpoint Cloud Computing
#pregunta 5
resp_cloud_computing.status_code

200

In [19]:
resp_analitica_datos=requests.get("https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/76403?tip=AM")

In [20]:
#endpoint Uso y analítica de datos: ERP, CRM, BI, etc
# Pregunta 5

resp_analitica_datos.status_code

200

2) Imprimir con .json() la información obtenida

In [21]:
#"Enséñame el contenido de esta respuesta en formato Python."
resp_empresas_tic.json
resp_cifra_de_negocio.json
resp_valor_añadido.json
resp_num_ocupados.json
resp_coste_trabajador.json
resp_ia.json
resp_cloud_computing.json
resp_analitica_datos.json

In [22]:
print(resp_empresas_tic.json())
print(resp_cifra_de_negocio.json())
print(resp_valor_añadido.json())
print(resp_num_ocupados.json())
print(resp_coste_trabajador.json())
print(resp_ia.json())
print(resp_cloud_computing.json())
print(resp_analitica_datos.json())

[{'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680', 'Codigo': '1industriasmanufacturerasticcnae261126122620263026402680'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 1236.0}]}, {'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680', 'Codigo': '1industriasmanufacturerasticcnae261126122620263026402680'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 1282.0}]}, {'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680', 'Codigo': '1industriasmanufacturerasticcnae261126122620263026402680'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 1342.0}]}, {'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680', 'Codigo': '1industriasmanufacturerasticcnae261126122620263026402680'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 1355.0}]}, {'Nombre': '2. SERVICIOS, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2. SERVICIOS', 'Codigo': '2servicios'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 81087.0}]}, {'Nombre': '2. SERVICIOS, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2. SERVICIOS', 'Codigo': '2servicios'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 75546.0}]}, {'Nombre': '2. SERVICIOS, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2. SERVICIOS', 'Codigo': '2servicios'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 73712.0}]}, {'Nombre': '2. SERVICIOS, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2. SERVICIOS', 'Codigo': '2servicios'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 71089.0}]}, {'Nombre': '2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652', 'Codigo': '2aindustriascomercialesticcnae46514652'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 3694.0}]}, {'Nombre': '2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652', 'Codigo': '2aindustriascomercialesticcnae46514652'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 3895.0}]}, {'Nombre': '2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652', 'Codigo': '2aindustriascomercialesticcnae46514652'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 4090.0}]}, {'Nombre': '2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652', 'Codigo': '2aindustriascomercialesticcnae46514652'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 4213.0}]}, {'Nombre': '2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829', 'Codigo': '2b1industriasdeserviciosticediciondeprogramasinformaticoscnae58215829'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 6524.0}]}, {'Nombre': '2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829', 'Codigo': '2b1industriasdeserviciosticediciondeprogramasinformaticoscnae58215829'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 5856.0}]}, {'Nombre': '2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829', 'Codigo': '2b1industriasdeserviciosticediciondeprogramasinformaticoscnae58215829'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 5596.0}]}, {'Nombre': '2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829', 'Codigo': '2b1industriasdeserviciosticediciondeprogramasinformaticoscnae58215829'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 5287.0}]}, {'Nombre': '2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190', 'Codigo': '2b2industriasdeserviciostictelecomunicacionescnae6110612061306190'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 6575.0}]}, {'Nombre': '2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190', 'Codigo': '2b2industriasdeserviciostictelecomunicacionescnae6110612061306190'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 6494.0}]}, {'Nombre': '2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190', 'Codigo': '2b2industriasdeserviciostictelecomunicacionescnae6110612061306190'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 6722.0}]}, {'Nombre': '2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190', 'Codigo': '2b2industriasdeserviciostictelecomunicacionescnae6110612061306190'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 6580.0}]}, {'Nombre': '2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209', 'Codigo': '2b3industriasdeserviciosticprogramacionconsultoriayotrasactividadesrelacionadasconlainformaticacnae6201620262036209'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 46951.0}]}, {'Nombre': '2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209', 'Codigo': '2b3industriasdeserviciosticprogramacionconsultoriayotrasactividadesrelacionadasconlainformaticacnae6201620262036209'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 42980.0}]}, {'Nombre': '2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209', 'Codigo': '2b3industriasdeserviciosticprogramacionconsultoriayotrasactividadesrelacionadasconlainformaticacnae6201620262036209'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 41385.0}]}, {'Nombre': '2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209', 'Codigo': '2b3industriasdeserviciosticprogramacionconsultoriayotrasactividadesrelacionadasconlainformaticacnae6201620262036209'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 39421.0}]}, {'Nombre': '2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312', 'Codigo': '2b4industriasdeserviciosticportaleswebprocesamientodedatoshostingyactividadesrelacionadascnae63116312'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 6522.0}]}, {'Nombre': '2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312', 'Codigo': '2b4industriasdeserviciosticportaleswebprocesamientodedatoshostingyactividadesrelacionadascnae63116312'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 5993.0}]}, {'Nombre': '2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312', 'Codigo': '2b4industriasdeserviciosticportaleswebprocesamientodedatoshostingyactividadesrelacionadascnae63116312'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 5878.0}]}, {'Nombre': '2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312', 'Codigo': '2b4industriasdeserviciosticportaleswebprocesamientodedatoshostingyactividadesrelacionadascnae63116312'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 5756.0}]}, {'Nombre': '2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512', 'Codigo': '2b5industriasdeserviciosticreparaciondeordenadoresyequiposdecomunicacioncnae95119512'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 10821.0}]}, {'Nombre': '2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512', 'Codigo': '2b5industriasdeserviciosticreparaciondeordenadoresyequiposdecomunicacioncnae95119512'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 10328.0}]}, {'Nombre': '2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512', 'Codigo': '2b5industriasdeserviciosticreparaciondeordenadoresyequiposdecomunicacioncnae95119512'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 10041.0}]}, {'Nombre': '2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': '2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512', 'Codigo': '2b5industriasdeserviciosticreparaciondeordenadoresyequiposdecomunicacioncnae95119512'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 9832.0}]}, {'Nombre': 'TOTAL SECTOR TIC, 2024', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': 'TOTAL SECTOR TIC', 'Codigo': 'totalsectortic'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}], 'Data': [{'Valor': 82323.0}]}, {'Nombre': 'TOTAL SECTOR TIC, 2023', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': 'TOTAL SECTOR TIC', 'Codigo': 'totalsectortic'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2023', 'Codigo': '2023'}], 'Data': [{'Valor': 76828.0}]}, {'Nombre': 'TOTAL SECTOR TIC, 2022', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': 'TOTAL SECTOR TIC', 'Codigo': 'totalsectortic'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2022', 'Codigo': '2022'}], 'Data': [{'Valor': 75054.0}]}, {'Nombre': 'TOTAL SECTOR TIC, 2021', 'MetaData': [{'T3_Variable': 'Rama de actividad', 'Nombre': 'TOTAL SECTOR TIC', 'Codigo': 'totalsectortic'}, {'T3_Variable': 'Periodo de referencia', 'Nombre': '2021', 'Codigo': '2021'}], 'Data': [{'Valor': 72444.0}]}]

In [23]:
#guardamos los json en una variable
empresas_tic = resp_empresas_tic.json()
cifra_negocio = resp_cifra_de_negocio.json()
valor_añadido = resp_valor_añadido.json()
num_ocupados = resp_num_ocupados.json()
coste_trabajador = resp_coste_trabajador.json()
ia = resp_ia.json()
cloud_computing = resp_cloud_computing.json()
analitica_datos = resp_analitica_datos.json()

3) Evaluar la lista o el objeto devuelto para saber, de manera general, que contiene el json devuelto

In [24]:
type(empresas_tic)

list

In [25]:
len(empresas_tic)
#elementos hay dentro de la lista.

36

In [26]:
empresas_tic[0]
#ver primer elemento de la lista

{'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2024',
 'MetaData': [{'T3_Variable': 'Rama de actividad',
   'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680',
   'Codigo': '1industriasmanufacturerasticcnae261126122620263026402680'},
  {'T3_Variable': 'Periodo de referencia',
   'Nombre': '2024',
   'Codigo': '2024'}],
 'Data': [{'Valor': 1236.0}]}

In [27]:
type(empresas_tic[0])
#Ver el tipo del primer elemento

dict

In [28]:
empresas_tic[0].keys()

dict_keys(['Nombre', 'MetaData', 'Data'])

In [29]:
empresas_tic[25].keys()

dict_keys(['Nombre', 'MetaData', 'Data'])

In [30]:
empresas_tic[0]["Nombre"]

'1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2024'

In [31]:
empresas_tic[0]["MetaData"]

[{'T3_Variable': 'Rama de actividad',
  'Nombre': '1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680',
  'Codigo': '1industriasmanufacturerasticcnae261126122620263026402680'},
 {'T3_Variable': 'Periodo de referencia', 'Nombre': '2024', 'Codigo': '2024'}]

In [32]:
empresas_tic[0]["Data"]

[{'Valor': 1236.0}]

In [33]:
import pandas as pd

In [34]:
pd.DataFrame(empresas_tic)

,Nombre,MetaData,Data
0,"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 1236.0}]
1,"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 1282.0}]
2,"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 1342.0}]
3,"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 1355.0}]
4,"2. SERVICIOS, 2024","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 81087.0}]
5,"2. SERVICIOS, 2023","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 75546.0}]
6,"2. SERVICIOS, 2022","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 73712.0}]
7,"2. SERVICIOS, 2021","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 71089.0}]
8,"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 465...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 3694.0}]
9,"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 465...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 3895.0}]
10,"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 465...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 4090.0}]
11,"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 465...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 4213.0}]
12,2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 6524.0}]
13,2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 5856.0}]
14,2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 5596.0}]
15,2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 5287.0}]
16,2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNIC...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 6575.0}]
17,2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNIC...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 6494.0}]
18,2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNIC...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 6722.0}]
19,2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNIC...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 6580.0}]
20,2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 46951.0}]
21,2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 42980.0}]
22,2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 41385.0}]
23,2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 39421.0}]
24,2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WE...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 6522.0}]
25,2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WE...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 5993.0}]
26,2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WE...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 5878.0}]
27,2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WE...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 5756.0}]
28,2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 10821.0}]
29,2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 10328.0}]
30,2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 10041.0}]
31,2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION ...,"[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 9832.0}]
32,"TOTAL SECTOR TIC, 2024","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 82323.0}]
33,"TOTAL SECTOR TIC, 2023","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 76828.0}]
34,"TOTAL SECTOR TIC, 2022","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 75054.0}]
35,"TOTAL SECTOR TIC, 2021","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 72444.0}]

In [35]:
df_empresas_tic = pd.DataFrame(empresas_tic)

In [36]:
df_empresas_tic.head()

,Nombre,MetaData,Data
0,"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 1236.0}]
1,"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 1282.0}]
2,"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 1342.0}]
3,"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2...","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 1355.0}]
4,"2. SERVICIOS, 2024","[{'T3_Variable': 'Rama de actividad', 'Nombre'...",[{'Valor': 81087.0}]

In [ ]:
#nos devuelve como string
resp_empresas_tic.text

'[{"Nombre":"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680", "Codigo":"1industriasmanufacturerasticcnae261126122620263026402680"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":1236.0}\n]\n}\n,{"Nombre":"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680", "Codigo":"1industriasmanufacturerasticcnae261126122620263026402680"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":1282.0}\n]\n}\n,{"Nombre":"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680", "Codigo":"1industriasmanufacturerasticcnae261126122620263026402680"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":1342.0}\n]\n}\n,{"Nombre":"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"1. INDUSTRIAS MANUFACTURERAS TIC: CNAE 2611, 2612, 2620, 2630, 2640, 2680", "Codigo":"1industriasmanufacturerasticcnae261126122620263026402680"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":1355.0}\n]\n}\n,{"Nombre":"2. SERVICIOS, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2. SERVICIOS", "Codigo":"2servicios"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":81087.0}\n]\n}\n,{"Nombre":"2. SERVICIOS, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2. SERVICIOS", "Codigo":"2servicios"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":75546.0}\n]\n}\n,{"Nombre":"2. SERVICIOS, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2. SERVICIOS", "Codigo":"2servicios"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":73712.0}\n]\n}\n,{"Nombre":"2. SERVICIOS, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2. SERVICIOS", "Codigo":"2servicios"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":71089.0}\n]\n}\n,{"Nombre":"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652", "Codigo":"2aindustriascomercialesticcnae46514652"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":3694.0}\n]\n}\n,{"Nombre":"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652", "Codigo":"2aindustriascomercialesticcnae46514652"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":3895.0}\n]\n}\n,{"Nombre":"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652", "Codigo":"2aindustriascomercialesticcnae46514652"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":4090.0}\n]\n}\n,{"Nombre":"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.A INDUSTRIAS COMERCIALES TIC: CNAE 4651, 4652", "Codigo":"2aindustriascomercialesticcnae46514652"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":4213.0}\n]\n}\n,{"Nombre":"2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829", "Codigo":"2b1industriasdeserviciosticediciondeprogramasinformaticoscnae58215829"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":6524.0}\n]\n}\n,{"Nombre":"2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829", "Codigo":"2b1industriasdeserviciosticediciondeprogramasinformaticoscnae58215829"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":5856.0}\n]\n}\n,{"Nombre":"2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829", "Codigo":"2b1industriasdeserviciosticediciondeprogramasinformaticoscnae58215829"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":5596.0}\n]\n}\n,{"Nombre":"2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.1 INDUSTRIAS DE SERVICIOS TIC: EDICIÓN DE PROGRAMAS INFORMÁTICOS: CNAE 5821 , 5829", "Codigo":"2b1industriasdeserviciosticediciondeprogramasinformaticoscnae58215829"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":5287.0}\n]\n}\n,{"Nombre":"2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190", "Codigo":"2b2industriasdeserviciostictelecomunicacionescnae6110612061306190"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":6575.0}\n]\n}\n,{"Nombre":"2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190", "Codigo":"2b2industriasdeserviciostictelecomunicacionescnae6110612061306190"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":6494.0}\n]\n}\n,{"Nombre":"2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190", "Codigo":"2b2industriasdeserviciostictelecomunicacionescnae6110612061306190"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":6722.0}\n]\n}\n,{"Nombre":"2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.2 INDUSTRIAS DE SERVICIOS TIC: TELECOMUNICACIONES: CNAE 6110, 6120, 6130, 6190", "Codigo":"2b2industriasdeserviciostictelecomunicacionescnae6110612061306190"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":6580.0}\n]\n}\n,{"Nombre":"2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209", "Codigo":"2b3industriasdeserviciosticprogramacionconsultoriayotrasactividadesrelacionadasconlainformaticacnae6201620262036209"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":46951.0}\n]\n}\n,{"Nombre":"2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209", "Codigo":"2b3industriasdeserviciosticprogramacionconsultoriayotrasactividadesrelacionadasconlainformaticacnae6201620262036209"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":42980.0}\n]\n}\n,{"Nombre":"2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209", "Codigo":"2b3industriasdeserviciosticprogramacionconsultoriayotrasactividadesrelacionadasconlainformaticacnae6201620262036209"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":41385.0}\n]\n}\n,{"Nombre":"2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.3 INDUSTRIAS DE SERVICIOS TIC: PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA: CNAE 6201, 6202, 6203, 6209", "Codigo":"2b3industriasdeserviciosticprogramacionconsultoriayotrasactividadesrelacionadasconlainformaticacnae6201620262036209"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":39421.0}\n]\n}\n,{"Nombre":"2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312", "Codigo":"2b4industriasdeserviciosticportaleswebprocesamientodedatoshostingyactividadesrelacionadascnae63116312"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":6522.0}\n]\n}\n,{"Nombre":"2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312", "Codigo":"2b4industriasdeserviciosticportaleswebprocesamientodedatoshostingyactividadesrelacionadascnae63116312"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":5993.0}\n]\n}\n,{"Nombre":"2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312", "Codigo":"2b4industriasdeserviciosticportaleswebprocesamientodedatoshostingyactividadesrelacionadascnae63116312"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":5878.0}\n]\n}\n,{"Nombre":"2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.4 INDUSTRIAS DE SERVICIOS TIC: PORTALES WEB, PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES RELACIONADAS: CNAE 6311, 6312", "Codigo":"2b4industriasdeserviciosticportaleswebprocesamientodedatoshostingyactividadesrelacionadascnae63116312"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":5756.0}\n]\n}\n,{"Nombre":"2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512", "Codigo":"2b5industriasdeserviciosticreparaciondeordenadoresyequiposdecomunicacioncnae95119512"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":10821.0}\n]\n}\n,{"Nombre":"2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512", "Codigo":"2b5industriasdeserviciosticreparaciondeordenadoresyequiposdecomunicacioncnae95119512"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":10328.0}\n]\n}\n,{"Nombre":"2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512", "Codigo":"2b5industriasdeserviciosticreparaciondeordenadoresyequiposdecomunicacioncnae95119512"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":10041.0}\n]\n}\n,{"Nombre":"2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"2.B.5 INDUSTRIAS DE SERVICIOS TIC: REPARACION DE ORDENADORES Y EQUIPOS DE COMUNICACIÓN: CNAE 9511, 9512", "Codigo":"2b5industriasdeserviciosticreparaciondeordenadoresyequiposdecomunicacioncnae95119512"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":9832.0}\n]\n}\n,{"Nombre":"TOTAL SECTOR TIC, 2024", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"TOTAL SECTOR TIC", "Codigo":"totalsectortic"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2024", "Codigo":"2024"}\n]\n, "Data":[{"Valor":82323.0}\n]\n}\n,{"Nombre":"TOTAL SECTOR TIC, 2023", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"TOTAL SECTOR TIC", "Codigo":"totalsectortic"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2023", "Codigo":"2023"}\n]\n, "Data":[{"Valor":76828.0}\n]\n}\n,{"Nombre":"TOTAL SECTOR TIC, 2022", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"TOTAL SECTOR TIC", "Codigo":"totalsectortic"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2022", "Codigo":"2022"}\n]\n, "Data":[{"Valor":75054.0}\n]\n}\n,{"Nombre":"TOTAL SECTOR TIC, 2021", "MetaData":[{"T3_Variable":"Rama de actividad", "Nombre":"TOTAL SECTOR TIC", "Codigo":"totalsectortic"}\n,{"T3_Variable":"Periodo de referencia", "Nombre":"2021", "Codigo":"2021"}\n]\n, "Data":[{"Valor":72444.0}\n]\n}\n]\n'